version: "3"

services:
  app:
    build: .
    volumes:
      - ./db_vol:/db
      - ./config_vol:/config
      - ./urls:/urls
      - ./src:/app
    environment:
      PYTHONUNBUFFERED: 1
      RW_DB_PATH: /db/down-monitor.db
      RW_CONFIG_PATH: /config/config.yaml
